// <auto-generated />
using System;
using CncBendingMachine.DataApi.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CncBendingMachine.DataApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("CncBendingMachine.Core.Entities.BendingJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActiveSensorSide")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<double>("BallDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("CalculatedPistonPositionMm")
                        .HasColumnType("REAL");

                    b.Property<double>("CenterDistanceMm")
                        .HasColumnType("REAL");

                    b.Property<int>("ClampPressureBar")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletedPasos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentPaso")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailedAtPaso")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FinalLeftPositionMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("FinalRightPositionMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("FirstStepDistanceMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("MeasuredDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<int>("Method")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("PartLengthMm")
                        .HasColumnType("REAL");

                    b.Property<int>("PistonSpeedPercent")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ProfileA")
                        .HasColumnType("REAL");

                    b.Property<double>("ProfileB")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProfileG")
                        .HasColumnType("REAL");

                    b.Property<double?>("ProfileH")
                        .HasColumnType("REAL");

                    b.Property<double>("ProfileS")
                        .HasColumnType("REAL");

                    b.Property<int>("ProfileType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RotationSpeedPercent")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SafetyMarginMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("SlackDistanceMm")
                        .HasColumnType("REAL");

                    b.Property<int>("SlackPressureBar")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<double>("StepDistanceMm")
                        .HasColumnType("REAL");

                    b.Property<double>("TargetDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<double>("ThetaDeg")
                        .HasColumnType("REAL");

                    b.Property<double>("ToleranceMm")
                        .HasColumnType("REAL");

                    b.Property<int>("TotalPasos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValsCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("XA1")
                        .HasColumnType("REAL");

                    b.Property<double>("YA1")
                        .HasColumnType("REAL");

                    b.Property<double>("ZeroResetDistanceMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("BendingJobs", (string)null);
                });

            modelBuilder.Entity("CncBendingMachine.Core.Entities.BendingLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BendingJobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsError")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Value1")
                        .HasColumnType("REAL");

                    b.Property<double?>("Value2")
                        .HasColumnType("REAL");

                    b.Property<double?>("Value3")
                        .HasColumnType("REAL");

                    b.Property<string>("ValueLabels")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BendingJobId");

                    b.HasIndex("BendingJobId", "Timestamp");

                    b.ToTable("BendingLogs", (string)null);
                });

            modelBuilder.Entity("CncBendingMachine.Core.Entities.GonyeSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("LeftOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<double>("LowerOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<int>("ReferencePressureBar")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RightOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("UpperOffsetMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("GonyeSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LeftOffsetMm = 3.75,
                            LowerOffsetMm = 10.5,
                            ReferencePressureBar = 70,
                            RightOffsetMm = 3.75,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpperOffsetMm = 0.0
                        });
                });

            modelBuilder.Entity("CncBendingMachine.Core.Entities.MachineSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultActiveSensorSide")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultBallDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultCenterDistanceMm")
                        .HasColumnType("REAL");

                    b.Property<int>("DefaultClampPressureBar")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultPistonSpeedPercent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultRotationSpeedPercent")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefaultSafetyMarginMm")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultSlackDistanceMm")
                        .HasColumnType("REAL");

                    b.Property<int>("DefaultSlackPressureBar")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefaultThetaDeg")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultToleranceMm")
                        .HasColumnType("REAL");

                    b.Property<string>("DefaultValsCode")
                        .HasColumnType("TEXT");

                    b.Property<double>("DefaultXA1")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultYA1")
                        .HasColumnType("REAL");

                    b.Property<int>("LeftPistonMaxReg")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LeftPistonStrokeMm")
                        .HasColumnType("REAL");

                    b.Property<int>("LowerPistonMaxReg")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LowerPistonStrokeMm")
                        .HasColumnType("REAL");

                    b.Property<int>("PneumaticMaxReg")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PneumaticStrokeMm")
                        .HasColumnType("REAL");

                    b.Property<int>("RightPistonMaxReg")
                        .HasColumnType("INTEGER");

                    b.Property<double>("RightPistonStrokeMm")
                        .HasColumnType("REAL");

                    b.Property<double>("RollerDiameterMm")
                        .HasColumnType("REAL");

                    b.Property<int>("RotationEncoderPpr")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SafetyMarginMm")
                        .HasColumnType("REAL");

                    b.Property<double>("SlpisLMm")
                        .HasColumnType("REAL");

                    b.Property<double>("SlpisRulmanCapMm")
                        .HasColumnType("REAL");

                    b.Property<double>("SlpisZeroOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UpperPistonMaxReg")
                        .HasColumnType("INTEGER");

                    b.Property<double>("UpperPistonStrokeMm")
                        .HasColumnType("REAL");

                    b.Property<double>("ZeroResetDistanceMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MachineSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultActiveSensorSide = "Left",
                            DefaultBallDiameterMm = 220.0,
                            DefaultCenterDistanceMm = 300.81999999999999,
                            DefaultClampPressureBar = 155,
                            DefaultPistonSpeedPercent = 100,
                            DefaultRotationSpeedPercent = 100,
                            DefaultSafetyMarginMm = 50.0,
                            DefaultSlackDistanceMm = 0.20000000000000001,
                            DefaultSlackPressureBar = 157,
                            DefaultThetaDeg = 63.0,
                            DefaultToleranceMm = 0.10000000000000001,
                            DefaultXA1 = -493.0,
                            DefaultYA1 = 0.0,
                            LeftPistonMaxReg = 21093,
                            LeftPistonStrokeMm = 422.0,
                            LowerPistonMaxReg = 9732,
                            LowerPistonStrokeMm = 195.0,
                            PneumaticMaxReg = 13250,
                            PneumaticStrokeMm = 265.0,
                            RightPistonMaxReg = 21127,
                            RightPistonStrokeMm = 422.0,
                            RollerDiameterMm = 220.0,
                            RotationEncoderPpr = 1024,
                            SafetyMarginMm = 1.0,
                            SlpisLMm = 70.0,
                            SlpisRulmanCapMm = 35.0,
                            SlpisZeroOffsetMm = 0.0,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpperPistonMaxReg = 7981,
                            UpperPistonStrokeMm = 161.0,
                            ZeroResetDistanceMm = 690.0
                        });
                });

            modelBuilder.Entity("CncBendingMachine.Core.Entities.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactInfo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineProductionYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineVeAiCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MissingPartsCodes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PartsUsedCodes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Purpose")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingNote")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkDoneCodes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("ServiceRequests", (string)null);
                });

            modelBuilder.Entity("CncBendingMachine.Core.Entities.ServiceTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Type");

                    b.ToTable("ServiceTickets", (string)null);
                });

            modelBuilder.Entity("CncBendingMachine.Core.Entities.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LeftOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<double>("LowerOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxProfileAMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("RightOffsetMm")
                        .HasColumnType("REAL");

                    b.Property<int>("StageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StageNumber")
                        .IsUnique();

                    b.ToTable("Stages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gonye pozisyonu - Küçük kapasite",
                            DisplayOrder = 1,
                            IsActive = true,
                            LeftOffsetMm = 0.0,
                            LowerOffsetMm = 0.0,
                            MaxProfileAMm = 50.0,
                            Name = "Stage 1",
                            RightOffsetMm = 0.0,
                            StageNumber = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Orta kapasite",
                            DisplayOrder = 2,
                            IsActive = true,
                            LeftOffsetMm = 67.340000000000003,
                            LowerOffsetMm = 60.0,
                            MaxProfileAMm = 120.0,
                            Name = "Stage 2",
                            RightOffsetMm = 67.340000000000003,
                            StageNumber = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Büyük kapasite",
                            DisplayOrder = 3,
                            IsActive = true,
                            LeftOffsetMm = 134.68000000000001,
                            LowerOffsetMm = 120.0,
                            MaxProfileAMm = 250.0,
                            Name = "Stage 3",
                            RightOffsetMm = 134.68000000000001,
                            StageNumber = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
